[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "inference_lib"
version = "1"

[tool.setuptools.packages.find]
where = ["."]
include = ["inference_lib"]