[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "personal-lib-plot"
version = "1"
dependencies = [
	# personal-lib-ann-parser
	# personal-lib-pred-parser
	# personal-lib-mask-conversions
	# torch
	# detectron
	"opencv-python",
	"numpy",
]