[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "inference_lib"
version = "1"
dependencies = [
    "pyyaml",
    "tqdm",
    "opencv-python"
]

[tool.setuptools.packages.find]
where = ["."]
include = ["inference_lib"]